name: Membership Application

description: Apply to join the MCP Hub organization

title: "Please invite me to the MCP Hub"

labels: [✉️ github-invitation]

body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Enter your name or GitHub username
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: How did you learn about the MCP Hub team? What interests you about MCP Hub? Why would you like to join?
      placeholder: I would like to be part of the awesome team
    validations:
      required: false